#+title: Release 1.5.6
#+author: Maga

* Table of Content:toc:
- [[#release-notes-156][Release Notes 1.5.6]]
  - [[#renounce][Renounce]]
  - [[#ambush][Ambush]]
  - [[#awareness][Awareness]]
  - [[#archery][Archery]]
  - [[#traveling][Traveling]]
  - [[#stealth-specialization][Stealth Specialization]]
  - [[#sneaking][Sneaking]]
  - [[#poison][Poison]]
  - [[#group-roll][Group Roll]]
  - [[#overkill-protection][Overkill Protection]]
  - [[#minimum-perception-from-insight][Minimum Perception From Insight]]
  - [[#movement-cost][Movement Cost]]
  - [[#password-display][Password Display]]

* Release Notes 1.5.6

The following has been changed and/or modified in the game for this release.

** Renounce

This is a new command added to remove a players sanctuary. See man gen renounce for more details.

** Ambush

Ambush for stealth specialized characters has been reduced against other players.

Players now have memory after being ambushed and will have a higher awareness afterwards making it difficult to be ambushed again.

** Awareness

The practice requirements for awareness has been reduced greatly for non-ranger based characters.

** Archery

While shooting the archers parry is now reduced to zero.

** Traveling

The movement regeneration from traveling has been greatly reduced.

** Stealth Specialization

The movement cost of rooms has been increased from 1 to 75% of the actual movement cost of the room.

** Sneaking

Sneaking now requires an additional 25% movement cost of the room when active.

** Poison

Casting poison at a target while being engaged will no longer default to the target you are currently engaged with.

** Group Roll

Group Roll is now sorted by highest to lowest roll

** Overkill Protection

Overkill protection has been removed

** Minimum Perception From Insight

Each race now has a minimum amount of perception they can obtain while insighted. This means if you are insighted and wear -perception gear it will only drop to specific point. It's different for each playable race.

** Movement Cost

A global 20% increase to movement penalties

** Password Display

Your password will no longer be displayed on the screen at login.
